server:
  port: 8080
spring:
  cloud:
    gateway:
      routes:
        - id: demo-route
          uri: https://yuque.antfin.com
          predicates:
            - Path=/dashboard

management:
  endpoints:
    web:
      exposure:
        include=*: